// Lebensmittel-Datenbank
// p = Eiweiß (g), c = Kohlenhydrate (g), f = Fett (g) pro Einheit
// health: 1 (sehr ungesund) – 10 (sehr gesund)
const FOODS = [
  // Brot & Getreide
  { name: "Toastbrot", einheit: "Scheibe", kcal: 70, p: 2.3, c: 12.5, f: 1, health: 4, cat: "Brot" },
  { name: "Vollkorntoast", einheit: "Scheibe", kcal: 65, p: 3, c: 10.5, f: 1.2, health: 7, cat: "Brot" },
  { name: "Brötchen (Weizen)", einheit: "Stück", kcal: 180, p: 6, c: 36, f: 1.5, health: 4, cat: "Brot" },
  { name: "Vollkornbrötchen", einheit: "Stück", kcal: 190, p: 7, c: 32, f: 2.5, health: 7, cat: "Brot" },
  { name: "Roggenbrot", einheit: "Scheibe", kcal: 120, p: 4, c: 22, f: 1, health: 7, cat: "Brot" },
  { name: "Weißbrot", einheit: "Scheibe", kcal: 100, p: 3, c: 19, f: 0.8, health: 3, cat: "Brot" },
  { name: "Vollkornbrot", einheit: "Scheibe", kcal: 110, p: 4.5, c: 18, f: 1.5, health: 8, cat: "Brot" },
  { name: "Pumpernickel", einheit: "Scheibe", kcal: 80, p: 2.5, c: 15, f: 0.6, health: 8, cat: "Brot" },
  { name: "Bagel", einheit: "Stück", kcal: 270, p: 10, c: 53, f: 1.5, health: 4, cat: "Brot" },
  { name: "Croissant", einheit: "Stück", kcal: 260, p: 5, c: 26, f: 14, health: 2, cat: "Backwaren" },
  { name: "Knäckebrot", einheit: "Scheibe", kcal: 35, p: 1, c: 7, f: 0.3, health: 7, cat: "Brot" },
  { name: "Brezel", einheit: "Stück", kcal: 240, p: 7, c: 47, f: 2, health: 3, cat: "Backwaren" },
  { name: "Müsli", einheit: "Portion (50g)", kcal: 190, p: 5, c: 33, f: 4, health: 7, cat: "Frühstück" },
  { name: "Haferflocken", einheit: "Portion (50g)", kcal: 185, p: 7, c: 30, f: 3.5, health: 9, cat: "Frühstück" },
  { name: "Cornflakes", einheit: "Portion (40g)", kcal: 150, p: 3, c: 32, f: 0.4, health: 4, cat: "Frühstück" },
  { name: "Schoko-Cerealien", einheit: "Portion (40g)", kcal: 160, p: 3, c: 31, f: 2.5, health: 2, cat: "Frühstück" },
  { name: "Granola", einheit: "Portion (50g)", kcal: 220, p: 5, c: 30, f: 9, health: 6, cat: "Frühstück" },

  // Aufstriche
  { name: "Butter", einheit: "TL (5g)", kcal: 37, p: 0, c: 0, f: 4, health: 4, cat: "Aufstrich" },
  { name: "Margarine", einheit: "TL (5g)", kcal: 35, p: 0, c: 0, f: 3.8, health: 4, cat: "Aufstrich" },
  { name: "Marmelade", einheit: "TL (10g)", kcal: 25, p: 0, c: 6, f: 0, health: 3, cat: "Aufstrich" },
  { name: "Honig", einheit: "TL (10g)", kcal: 30, p: 0, c: 8, f: 0, health: 4, cat: "Aufstrich" },
  { name: "Nutella", einheit: "TL (15g)", kcal: 80, p: 1, c: 8.5, f: 4.5, health: 1, cat: "Aufstrich" },
  { name: "Erdnussbutter", einheit: "EL (15g)", kcal: 95, p: 4, c: 3, f: 8, health: 5, cat: "Aufstrich" },
  { name: "Frischkäse", einheit: "EL (20g)", kcal: 50, p: 1.5, c: 0.5, f: 5, health: 5, cat: "Aufstrich" },

  // Wurst
  { name: "Salami", einheit: "Scheibe", kcal: 30, p: 1.8, c: 0, f: 2.5, health: 3, cat: "Wurst" },
  { name: "Kochschinken", einheit: "Scheibe", kcal: 20, p: 3.5, c: 0, f: 0.7, health: 5, cat: "Wurst" },
  { name: "Rohschinken", einheit: "Scheibe", kcal: 25, p: 4, c: 0, f: 1, health: 4, cat: "Wurst" },
  { name: "Mortadella", einheit: "Scheibe", kcal: 35, p: 2, c: 0.2, f: 3, health: 3, cat: "Wurst" },
  { name: "Leberwurst", einheit: "EL (25g)", kcal: 80, p: 3, c: 0.5, f: 7.5, health: 3, cat: "Wurst" },
  { name: "Putenbrust (Aufschnitt)", einheit: "Scheibe", kcal: 12, p: 2.5, c: 0, f: 0.2, health: 6, cat: "Wurst" },
  { name: "Mettwurst", einheit: "Scheibe", kcal: 40, p: 1.5, c: 0, f: 3.8, health: 2, cat: "Wurst" },
  { name: "Bockwurst", einheit: "Stück", kcal: 240, p: 13, c: 1, f: 21, health: 3, cat: "Wurst" },

  // Käse
  { name: "Gouda", einheit: "Scheibe (30g)", kcal: 105, p: 7.5, c: 0, f: 8, health: 5, cat: "Käse" },
  { name: "Emmentaler", einheit: "Scheibe (30g)", kcal: 120, p: 8.5, c: 0, f: 9, health: 5, cat: "Käse" },
  { name: "Mozzarella", einheit: "Portion (50g)", kcal: 125, p: 9, c: 0.5, f: 9.5, health: 6, cat: "Käse" },
  { name: "Camembert", einheit: "Stück (30g)", kcal: 90, p: 6, c: 0, f: 7, health: 5, cat: "Käse" },
  { name: "Cheddar", einheit: "Scheibe (30g)", kcal: 125, p: 7.5, c: 0, f: 10, health: 4, cat: "Käse" },
  { name: "Brie", einheit: "Stück (30g)", kcal: 100, p: 6, c: 0, f: 8, health: 5, cat: "Käse" },
  { name: "Parmesan", einheit: "EL (10g)", kcal: 40, p: 3.5, c: 0, f: 3, health: 6, cat: "Käse" },
  { name: "Hüttenkäse", einheit: "Portion (100g)", kcal: 100, p: 13, c: 3, f: 4.5, health: 8, cat: "Käse" },
  { name: "Schmelzkäse", einheit: "Ecke (20g)", kcal: 55, p: 2, c: 0.5, f: 5, health: 3, cat: "Käse" },
  { name: "Feta", einheit: "Portion (50g)", kcal: 130, p: 7, c: 0.5, f: 11, health: 5, cat: "Käse" },

  // Eier & Milch
  { name: "Ei (gekocht)", einheit: "Stück", kcal: 80, p: 6.5, c: 0.5, f: 5.5, health: 8, cat: "Ei" },
  { name: "Spiegelei", einheit: "Stück", kcal: 110, p: 7, c: 0.5, f: 9, health: 6, cat: "Ei" },
  { name: "Rührei", einheit: "Portion (2 Eier)", kcal: 200, p: 14, c: 1, f: 16, health: 6, cat: "Ei" },
  { name: "Milch (3,5 %)", einheit: "Glas (200 ml)", kcal: 130, p: 7, c: 9.5, f: 7, health: 6, cat: "Milch" },
  { name: "Milch (1,5 %)", einheit: "Glas (200 ml)", kcal: 95, p: 7, c: 9.5, f: 3, health: 7, cat: "Milch" },
  { name: "Magermilch", einheit: "Glas (200 ml)", kcal: 70, p: 7, c: 10, f: 0.4, health: 7, cat: "Milch" },
  { name: "Sahne (Schlag)", einheit: "EL (15g)", kcal: 45, p: 0.3, c: 0.5, f: 4.5, health: 3, cat: "Milch" },
  { name: "Naturjoghurt", einheit: "Becher (150g)", kcal: 100, p: 6, c: 7, f: 5, health: 8, cat: "Milch" },
  { name: "Fruchtjoghurt", einheit: "Becher (150g)", kcal: 150, p: 5, c: 25, f: 2.5, health: 5, cat: "Milch" },
  { name: "Skyr", einheit: "Becher (150g)", kcal: 95, p: 17, c: 6, f: 0.3, health: 9, cat: "Milch" },
  { name: "Quark (mager)", einheit: "Portion (250g)", kcal: 170, p: 30, c: 10, f: 0.5, health: 9, cat: "Milch" },

  // Obst
  { name: "Apfel", einheit: "Stück", kcal: 80, p: 0.3, c: 19, f: 0.3, health: 9, cat: "Obst" },
  { name: "Banane", einheit: "Stück", kcal: 105, p: 1.3, c: 27, f: 0.3, health: 8, cat: "Obst" },
  { name: "Birne", einheit: "Stück", kcal: 100, p: 0.6, c: 25, f: 0.3, health: 9, cat: "Obst" },
  { name: "Orange", einheit: "Stück", kcal: 70, p: 1.3, c: 17, f: 0.2, health: 9, cat: "Obst" },
  { name: "Mandarine", einheit: "Stück", kcal: 40, p: 0.6, c: 10, f: 0.2, health: 9, cat: "Obst" },
  { name: "Trauben", einheit: "Portion (100g)", kcal: 70, p: 0.7, c: 17, f: 0.2, health: 7, cat: "Obst" },
  { name: "Erdbeeren", einheit: "Portion (150g)", kcal: 50, p: 1, c: 11, f: 0.5, health: 10, cat: "Obst" },
  { name: "Himbeeren", einheit: "Portion (125g)", kcal: 45, p: 1.5, c: 7, f: 0.4, health: 10, cat: "Obst" },
  { name: "Heidelbeeren", einheit: "Portion (125g)", kcal: 60, p: 1, c: 15, f: 0.5, health: 10, cat: "Obst" },
  { name: "Kirschen", einheit: "Portion (150g)", kcal: 95, p: 1.5, c: 22, f: 0.5, health: 9, cat: "Obst" },
  { name: "Pfirsich", einheit: "Stück", kcal: 50, p: 1, c: 12, f: 0.3, health: 9, cat: "Obst" },
  { name: "Pflaume", einheit: "Stück", kcal: 25, p: 0.4, c: 6, f: 0.2, health: 9, cat: "Obst" },
  { name: "Ananas", einheit: "Scheibe (100g)", kcal: 50, p: 0.5, c: 12, f: 0.1, health: 8, cat: "Obst" },
  { name: "Mango", einheit: "halbe Frucht", kcal: 100, p: 1, c: 25, f: 0.5, health: 8, cat: "Obst" },
  { name: "Wassermelone", einheit: "Stück (200g)", kcal: 60, p: 1.2, c: 15, f: 0.4, health: 9, cat: "Obst" },
  { name: "Kiwi", einheit: "Stück", kcal: 45, p: 0.9, c: 11, f: 0.3, health: 10, cat: "Obst" },
  { name: "Avocado", einheit: "halbe Frucht", kcal: 160, p: 2, c: 8, f: 15, health: 8, cat: "Obst" },
  { name: "Granatapfel", einheit: "Stück", kcal: 230, p: 4.5, c: 50, f: 3, health: 9, cat: "Obst" },

  // Gemüse
  { name: "Gurke", einheit: "Scheibe", kcal: 1, p: 0.05, c: 0.2, f: 0, health: 10, cat: "Gemüse" },
  { name: "Gurke (halbe)", einheit: "Stück", kcal: 30, p: 1.5, c: 6, f: 0.3, health: 10, cat: "Gemüse" },
  { name: "Tomate", einheit: "Stück", kcal: 22, p: 1, c: 4, f: 0.2, health: 9, cat: "Gemüse" },
  { name: "Cherrytomate", einheit: "Stück", kcal: 4, p: 0.2, c: 0.8, f: 0.05, health: 9, cat: "Gemüse" },
  { name: "Karotte", einheit: "Stück", kcal: 30, p: 0.7, c: 7, f: 0.2, health: 10, cat: "Gemüse" },
  { name: "Paprika", einheit: "Stück", kcal: 30, p: 1, c: 6, f: 0.3, health: 10, cat: "Gemüse" },
  { name: "Salatblatt", einheit: "Blatt", kcal: 2, p: 0.2, c: 0.3, f: 0, health: 10, cat: "Gemüse" },
  { name: "Gemischter Salat", einheit: "Schüssel", kcal: 50, p: 2, c: 8, f: 1, health: 10, cat: "Gemüse" },
  { name: "Spinat", einheit: "Portion (200g)", kcal: 45, p: 6, c: 7, f: 0.5, health: 10, cat: "Gemüse" },
  { name: "Brokkoli", einheit: "Portion (200g)", kcal: 70, p: 6, c: 13, f: 0.8, health: 10, cat: "Gemüse" },
  { name: "Blumenkohl", einheit: "Portion (200g)", kcal: 50, p: 4, c: 10, f: 0.6, health: 10, cat: "Gemüse" },
  { name: "Zucchini", einheit: "Stück", kcal: 30, p: 2.5, c: 6, f: 0.3, health: 9, cat: "Gemüse" },
  { name: "Aubergine", einheit: "Stück", kcal: 50, p: 2, c: 12, f: 0.4, health: 9, cat: "Gemüse" },
  { name: "Champignons", einheit: "Portion (100g)", kcal: 22, p: 3, c: 3, f: 0.4, health: 9, cat: "Gemüse" },
  { name: "Zwiebel", einheit: "Stück", kcal: 40, p: 1.5, c: 10, f: 0.1, health: 8, cat: "Gemüse" },
  { name: "Kartoffel (gekocht)", einheit: "Stück (150g)", kcal: 115, p: 3, c: 26, f: 0.2, health: 7, cat: "Beilage" },
  { name: "Süßkartoffel", einheit: "Stück (200g)", kcal: 180, p: 3, c: 41, f: 0.3, health: 9, cat: "Beilage" },
  { name: "Mais", einheit: "Portion (100g)", kcal: 100, p: 3.5, c: 22, f: 1.2, health: 6, cat: "Gemüse" },
  { name: "Erbsen", einheit: "Portion (100g)", kcal: 85, p: 5, c: 14, f: 0.4, health: 8, cat: "Gemüse" },
  { name: "Bohnen (grün)", einheit: "Portion (200g)", kcal: 70, p: 4, c: 14, f: 0.4, health: 9, cat: "Gemüse" },
  { name: "Linsen (gekocht)", einheit: "Portion (200g)", kcal: 230, p: 18, c: 40, f: 0.8, health: 10, cat: "Gemüse" },
  { name: "Sauerkraut", einheit: "Portion (200g)", kcal: 40, p: 3, c: 8, f: 0.4, health: 8, cat: "Gemüse" },

  // Fleisch & Fisch
  { name: "Hähnchenbrust", einheit: "Portion (150g)", kcal: 180, p: 35, c: 0, f: 4, health: 8, cat: "Fleisch" },
  { name: "Putenbrust", einheit: "Portion (150g)", kcal: 170, p: 36, c: 0, f: 2.5, health: 9, cat: "Fleisch" },
  { name: "Rinderhack (mager)", einheit: "Portion (150g)", kcal: 280, p: 30, c: 0, f: 18, health: 5, cat: "Fleisch" },
  { name: "Schweineschnitzel", einheit: "Stück (150g)", kcal: 220, p: 30, c: 0, f: 11, health: 5, cat: "Fleisch" },
  { name: "Schnitzel (paniert)", einheit: "Stück (180g)", kcal: 420, p: 30, c: 18, f: 24, health: 3, cat: "Fleisch" },
  { name: "Rindersteak", einheit: "Portion (200g)", kcal: 400, p: 50, c: 0, f: 22, health: 6, cat: "Fleisch" },
  { name: "Bratwurst", einheit: "Stück", kcal: 280, p: 12, c: 1, f: 25, health: 2, cat: "Fleisch" },
  { name: "Frikadelle", einheit: "Stück", kcal: 260, p: 18, c: 6, f: 18, health: 3, cat: "Fleisch" },
  { name: "Lachs", einheit: "Filet (150g)", kcal: 310, p: 30, c: 0, f: 21, health: 9, cat: "Fisch" },
  { name: "Thunfisch (Dose)", einheit: "Dose (150g)", kcal: 175, p: 38, c: 0, f: 2, health: 8, cat: "Fisch" },
  { name: "Forelle", einheit: "Filet (150g)", kcal: 180, p: 30, c: 0, f: 6, health: 9, cat: "Fisch" },
  { name: "Hering", einheit: "Filet (100g)", kcal: 220, p: 18, c: 0, f: 16, health: 8, cat: "Fisch" },
  { name: "Garnelen", einheit: "Portion (150g)", kcal: 110, p: 25, c: 0, f: 1, health: 9, cat: "Fisch" },

  // Pasta, Reis, Beilagen
  { name: "Spaghetti (gekocht)", einheit: "Portion (200g)", kcal: 310, p: 11, c: 62, f: 1.8, health: 5, cat: "Beilage" },
  { name: "Vollkorn-Pasta (gekocht)", einheit: "Portion (200g)", kcal: 290, p: 13, c: 56, f: 2, health: 7, cat: "Beilage" },
  { name: "Penne (gekocht)", einheit: "Portion (200g)", kcal: 310, p: 11, c: 62, f: 1.8, health: 5, cat: "Beilage" },
  { name: "Reis weiß (gekocht)", einheit: "Portion (200g)", kcal: 260, p: 5, c: 56, f: 0.6, health: 5, cat: "Beilage" },
  { name: "Reis Vollkorn (gekocht)", einheit: "Portion (200g)", kcal: 230, p: 5, c: 45, f: 1.8, health: 8, cat: "Beilage" },
  { name: "Couscous (gekocht)", einheit: "Portion (200g)", kcal: 220, p: 8, c: 46, f: 0.3, health: 6, cat: "Beilage" },
  { name: "Quinoa (gekocht)", einheit: "Portion (200g)", kcal: 240, p: 9, c: 42, f: 4, health: 9, cat: "Beilage" },
  { name: "Kartoffelpüree", einheit: "Portion (200g)", kcal: 180, p: 4, c: 30, f: 5, health: 5, cat: "Beilage" },
  { name: "Pommes frites", einheit: "Portion (150g)", kcal: 460, p: 5, c: 55, f: 24, health: 2, cat: "Beilage" },
  { name: "Bratkartoffeln", einheit: "Portion (200g)", kcal: 300, p: 5, c: 38, f: 14, health: 4, cat: "Beilage" },
  { name: "Knödel", einheit: "Stück", kcal: 150, p: 4, c: 30, f: 1.5, health: 4, cat: "Beilage" },
  { name: "Spätzle", einheit: "Portion (200g)", kcal: 350, p: 12, c: 60, f: 6, health: 5, cat: "Beilage" },

  // Fast Food & Fertiggerichte
  { name: "Pizza Margherita", einheit: "Stück (300g)", kcal: 700, p: 27, c: 90, f: 24, health: 4, cat: "Fast Food" },
  { name: "Pizza Salami", einheit: "Stück (320g)", kcal: 860, p: 32, c: 90, f: 38, health: 2, cat: "Fast Food" },
  { name: "Burger (Standard)", einheit: "Stück", kcal: 510, p: 25, c: 40, f: 28, health: 3, cat: "Fast Food" },
  { name: "Cheeseburger", einheit: "Stück", kcal: 300, p: 15, c: 33, f: 13, health: 3, cat: "Fast Food" },
  { name: "Big Mac", einheit: "Stück", kcal: 550, p: 25, c: 45, f: 30, health: 2, cat: "Fast Food" },
  { name: "Döner Kebab", einheit: "Stück", kcal: 650, p: 35, c: 60, f: 30, health: 4, cat: "Fast Food" },
  { name: "Currywurst mit Pommes", einheit: "Portion", kcal: 850, p: 22, c: 70, f: 50, health: 2, cat: "Fast Food" },
  { name: "Hotdog", einheit: "Stück", kcal: 290, p: 11, c: 24, f: 18, health: 2, cat: "Fast Food" },
  { name: "Lasagne", einheit: "Portion (400g)", kcal: 560, p: 30, c: 50, f: 25, health: 4, cat: "Fertiggericht" },
  { name: "Tiefkühlpizza", einheit: "Stück (350g)", kcal: 800, p: 30, c: 90, f: 32, health: 3, cat: "Fertiggericht" },
  { name: "Maultaschen", einheit: "Portion (300g)", kcal: 420, p: 22, c: 50, f: 14, health: 5, cat: "Fertiggericht" },

  // Süßes
  { name: "Schokolade Vollmilch", einheit: "Riegel (30g)", kcal: 165, p: 2, c: 17, f: 9.5, health: 2, cat: "Süßes" },
  { name: "Schokolade Zartbitter", einheit: "Riegel (30g)", kcal: 165, p: 2, c: 14, f: 11, health: 3, cat: "Süßes" },
  { name: "Schokolade (ganze Tafel)", einheit: "Tafel (100g)", kcal: 550, p: 6, c: 57, f: 32, health: 2, cat: "Süßes" },
  { name: "Gummibärchen", einheit: "Handvoll (40g)", kcal: 140, p: 3, c: 31, f: 0, health: 1, cat: "Süßes" },
  { name: "Kekse", einheit: "Stück", kcal: 50, p: 0.7, c: 7, f: 2, health: 2, cat: "Süßes" },
  { name: "Donut", einheit: "Stück", kcal: 280, p: 4, c: 32, f: 15, health: 1, cat: "Süßes" },
  { name: "Käsekuchen", einheit: "Stück", kcal: 320, p: 6, c: 30, f: 20, health: 3, cat: "Süßes" },
  { name: "Apfelkuchen", einheit: "Stück", kcal: 280, p: 3, c: 38, f: 13, health: 3, cat: "Süßes" },
  { name: "Eis (Kugel)", einheit: "Kugel", kcal: 110, p: 2, c: 14, f: 5.5, health: 3, cat: "Süßes" },
  { name: "Magnum-Eis", einheit: "Stück", kcal: 260, p: 3, c: 25, f: 17, health: 1, cat: "Süßes" },
  { name: "Müsliriegel", einheit: "Riegel", kcal: 120, p: 2, c: 18, f: 4.5, health: 4, cat: "Süßes" },
  { name: "Schokoriegel (Mars/Snickers)", einheit: "Riegel", kcal: 250, p: 4, c: 33, f: 11, health: 1, cat: "Süßes" },
  { name: "Pudding", einheit: "Becher", kcal: 140, p: 4, c: 23, f: 4, health: 4, cat: "Süßes" },

  // Snacks
  { name: "Chips", einheit: "Handvoll (30g)", kcal: 160, p: 2, c: 16, f: 10, health: 1, cat: "Snack" },
  { name: "Chips (große Tüte)", einheit: "Tüte (175g)", kcal: 950, p: 12, c: 95, f: 60, health: 1, cat: "Snack" },
  { name: "Salzstangen", einheit: "Handvoll (30g)", kcal: 110, p: 3, c: 23, f: 1, health: 3, cat: "Snack" },
  { name: "Erdnüsse", einheit: "Handvoll (30g)", kcal: 175, p: 8, c: 5, f: 14, health: 6, cat: "Snack" },
  { name: "Mandeln", einheit: "Handvoll (30g)", kcal: 175, p: 6, c: 6, f: 15, health: 8, cat: "Snack" },
  { name: "Cashews", einheit: "Handvoll (30g)", kcal: 170, p: 5, c: 9, f: 13, health: 7, cat: "Snack" },
  { name: "Walnüsse", einheit: "Handvoll (30g)", kcal: 200, p: 5, c: 4, f: 19, health: 9, cat: "Snack" },
  { name: "Studentenfutter", einheit: "Handvoll (30g)", kcal: 145, p: 4, c: 13, f: 9, health: 6, cat: "Snack" },
  { name: "Popcorn (süß)", einheit: "Portion (50g)", kcal: 220, p: 3, c: 40, f: 6, health: 3, cat: "Snack" },

  // Getränke
  { name: "Wasser", einheit: "Glas (250 ml)", kcal: 0, p: 0, c: 0, f: 0, health: 10, cat: "Getränk" },
  { name: "Apfelsaft", einheit: "Glas (250 ml)", kcal: 115, p: 0.3, c: 28, f: 0, health: 4, cat: "Getränk" },
  { name: "Orangensaft", einheit: "Glas (250 ml)", kcal: 110, p: 1.8, c: 25, f: 0.3, health: 5, cat: "Getränk" },
  { name: "Cola", einheit: "Glas (250 ml)", kcal: 105, p: 0, c: 27, f: 0, health: 1, cat: "Getränk" },
  { name: "Cola light/zero", einheit: "Glas (250 ml)", kcal: 1, p: 0, c: 0, f: 0, health: 3, cat: "Getränk" },
  { name: "Fanta", einheit: "Glas (250 ml)", kcal: 120, p: 0, c: 29, f: 0, health: 1, cat: "Getränk" },
  { name: "Schorle (Apfel)", einheit: "Glas (250 ml)", kcal: 55, p: 0.2, c: 13, f: 0, health: 6, cat: "Getränk" },
  { name: "Kaffee schwarz", einheit: "Tasse", kcal: 2, p: 0.1, c: 0, f: 0, health: 8, cat: "Getränk" },
  { name: "Kaffee mit Milch", einheit: "Tasse", kcal: 30, p: 1.5, c: 2, f: 1.5, health: 7, cat: "Getränk" },
  { name: "Cappuccino", einheit: "Tasse", kcal: 80, p: 4, c: 6, f: 4, health: 6, cat: "Getränk" },
  { name: "Latte Macchiato", einheit: "Glas", kcal: 130, p: 7, c: 10, f: 7, health: 6, cat: "Getränk" },
  { name: "Tee (ohne Zucker)", einheit: "Tasse", kcal: 2, p: 0, c: 0, f: 0, health: 10, cat: "Getränk" },
  { name: "Bier (Pils)", einheit: "Glas (0,3 l)", kcal: 130, p: 1, c: 10, f: 0, health: 2, cat: "Getränk" },
  { name: "Bier (Pils, 0,5 l)", einheit: "Glas (0,5 l)", kcal: 215, p: 1.5, c: 17, f: 0, health: 2, cat: "Getränk" },
  { name: "Weizenbier", einheit: "Glas (0,5 l)", kcal: 240, p: 2.5, c: 18, f: 0, health: 2, cat: "Getränk" },
  { name: "Wein rot", einheit: "Glas (200 ml)", kcal: 170, p: 0.2, c: 5, f: 0, health: 3, cat: "Getränk" },
  { name: "Wein weiß", einheit: "Glas (200 ml)", kcal: 160, p: 0.2, c: 2, f: 0, health: 3, cat: "Getränk" },
  { name: "Sekt", einheit: "Glas (100 ml)", kcal: 85, p: 0.2, c: 3, f: 0, health: 2, cat: "Getränk" },

  // Sonstiges
  { name: "Olivenöl", einheit: "EL (10 ml)", kcal: 90, p: 0, c: 0, f: 10, health: 7, cat: "Fett" },
  { name: "Mayonnaise", einheit: "EL (15g)", kcal: 110, p: 0.2, c: 0.5, f: 12, health: 2, cat: "Sauce" },
  { name: "Ketchup", einheit: "EL (15g)", kcal: 18, p: 0.2, c: 4, f: 0, health: 3, cat: "Sauce" },
  { name: "Senf", einheit: "TL (5g)", kcal: 5, p: 0.3, c: 0.3, f: 0.3, health: 6, cat: "Sauce" },
  { name: "Salatdressing", einheit: "EL (15 ml)", kcal: 60, p: 0.2, c: 2, f: 5.5, health: 4, cat: "Sauce" },
  { name: "Suppe (Brühe)", einheit: "Teller", kcal: 50, p: 3, c: 5, f: 1.5, health: 7, cat: "Suppe" },
  { name: "Tomatensuppe", einheit: "Teller", kcal: 150, p: 4, c: 22, f: 5, health: 6, cat: "Suppe" },
  { name: "Kartoffelsuppe", einheit: "Teller", kcal: 220, p: 6, c: 28, f: 9, health: 6, cat: "Suppe" },
];

// Aktivitätslevel-Faktoren — kompatibel mit alten Settings
if (typeof window !== 'undefined') window.FOODS = FOODS;
